spring.application.name=order-service

server.port=8082

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

master-data.base-url=${MASTER_DATA_BASE_URL:http://localhost:8081}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info
