spring.application.name=master-data-service

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/logistics
spring.datasource.username=logistics
spring.datasource.password=logistics
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info,metrics